# config.yaml

company_name: "backmarket"
base_url: "https://fr.trustpilot.com/review/www.{company_name}.fr"

paths:
  base_dir: "."
  parameters_dir: "{base_dir}/parameters"
  data_dir: "{base_dir}/data"
  logs_dir: "{base_dir}/logs"
  raw_data_dir: "{data_dir}/raw"
  cleaned_data_dir: "{data_dir}/cleaned"
  full_reviews_dir: "{data_dir}/full"
  archive_dir: "{data_dir}/archive"

files:
  max_page_param_file: "{parameters_dir}/max_page.txt"
  log_file: "{logs_dir}/reviews_pipeline.log"

http_headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.5"
  Connection: "keep-alive"
  Upgrade-Insecure-Requests: "1"
  Cache-Control: "max-age=0"

request_settings:
  timeout: 10
  retry_count: 3
  retry_delay: 2
  max_pages_to_scrape: 10
  delay_between_requests: 1

review_keys:
  - "id"
  - "title"
  - "review"
  - "rating"
  - "reply"
  - "experienceDate"
  - "createdDateTime"
  - "publishedDate"
  - "replyPublishedDate"

stop_words_to_add:
  - "être"
  - "leur"
  - "leurs"
  - "avoir"
  - "cela"
  - "les"
  - "de"
  - "pour"
  - "des"
  - "cette"
  - "a"
  - "j'ai"
  - "car"
  - "c'est"
  - "chez"
  - "tout"
  - "fait"
  - "chez"
  - "donc"
  - "n'est"
  - "si"
  - "alors"
  - "n'ai"
  - "faire"
  - "deux"
  - "comme"
  - "jour"
  - "tr"
  - "si"
  - "ue"
  - "back"
  - "backmarket"
  - "market"

min_review_length: 4

sentiment_thresholds:
  positive: 4
  neutral: 3
  negative: 2

spacy_model: "fr_core_news_sm"